# Data Preprocessing

## Notebook 3: Preparing the Data for Machine Learning

In this notebook, we prepare the employee attrition dataset for machine learning by cleaning the data, removing unnecessary features, encoding categorical variables, splitting the dataset into training and testing sets, and scaling numerical features where appropriate.

The objective is to transform the raw dataset into a format that machine learning algorithms can understand and learn from.

## 1. Import Libraries

We import the libraries required for data preprocessing, including data manipulation, data splitting, feature encoding, and feature scaling.

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

## 2. Load the Dataset

Load the employee attrition dataset into a pandas DataFrame for preprocessing.

In [5]:
df = pd.read_csv("../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

## 3. Remove Unnecessary Columns

Some columns do not contribute to predicting employee attrition because they either contain the same value for every employee or serve only as unique identifiers.

Removing these columns reduces unnecessary information and simplifies the dataset.

In [6]:
df.drop(
    columns=[
        "EmployeeCount",
        "EmployeeNumber",
        "StandardHours"
    ],
    inplace=True
)

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

## 4. Separate Features and Target

Separate the dataset into input features (X) and the target variable (y).

The features contain the information used to make predictions, while the target variable represents whether an employee left the company.

In [7]:
X = df.drop("Attrition", axis=1)

y = df["Attrition"]

In [26]:
print(X.shape)
print(y.shape)

(1470, 31)
(1470,)

## 5. Encode the Target Variable

Machine learning algorithms require numerical target values.

The Attrition column is converted from text labels ("Yes" and "No") into numerical values.

In [8]:
label_encoder = LabelEncoder()

y = label_encoder.fit_transform(y)

In [9]:
print(y[:10])

[1 0 1 0 0 0 0 0 0 0]

## 6. Encode Categorical Features

Categorical features are converted into numerical representations using One-Hot Encoding.

This prevents the model from interpreting categories as having an ordinal relationship.

In [10]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [11]:
X.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,2,94,3,2,4,5993,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,3,61,2,2,2,5130,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,4,92,2,1,3,2090,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,4,56,3,1,3,2909,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,40,3,1,2,3468,...,1,0,0,0,0,0,0,1,0,0

## 7. Split the Dataset

Before training a machine learning model, we split the dataset into training and testing sets.

- The **training set** is used to teach the model patterns from the data.
- The **testing set** is used to evaluate how well the model performs on unseen data.

This helps measure the model's ability to generalize rather than simply memorizing the training data.

In [12]:
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

Training features: (1176, 44)
Testing features: (294, 44)
Training labels: (1176,)
Testing labels: (294,)

## 8. Feature Scaling

Machine learning algorithms often perform better when numerical features are on a similar scale.

Since our dataset contains numerical features with different ranges (for example, Age and MonthlyIncome), we standardize the numerical features using StandardScaler.

Feature scaling is particularly important for algorithms such as Logistic Regression, Support Vector Machine (SVM), and K-Nearest Neighbors (KNN).

In [15]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(1176, 44)
(294, 44)